language: node_js
node_js:
  - '0.10'
  - '0.11'

env:
  global:
    - CGMINER_HOST=localhost
    - CGMINER_PORT=4028

before_install:
  - bash install.sh
  - sleep 20

after_script:
  - sleep 5

notifications:
  email: false

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: wMmlcX3in5XrYeYwYxiLzCXOMN3XKmzs05OBio/zHkRfx2RaftQdGqqxg3ZzVn+k8PMDScW6DGf6UcdACWZLn3riPV0tlbqUh9M6XCf9t49WeqrOJQMTR1cMXsSk9m+EHAiE1wwalP/i7H/XDTNBe//bwHmqnUEG29VOCOsOon0=
  on:
    tags: true
    all_branches: true
